# Generated by Django 4.1.5 on 2023-01-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('initAmount', models.IntegerField()),
                ('remain', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='cate_id')),
            ],
        ),
    ]
