# Generated by Django 4.1.5 on 2023-02-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
